package com.mafia.game;

public enum GameState {
    WAITING, DAY_MAYOR_ELECTION, DAY_DISCUSSION, DAY_NOMINATION, DAY_TRIAL, DAY_VOTE,
    NIGHT_MAFIA, NIGHT_DOCTOR, NIGHT_POLICE, NIGHT_RESOLVE, ENDED
}
